kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app1Operator
rules:
- apiGroups: ["*"] 
  resources:
    - pods
    - services
    - deployments
    - configmaps 
    - ingress
  verbs:
    - get
    - watch
    - list
    - create
    - delete
- apiGroups: ["*"] 
  resources:
    - secrets
  verbs:
    - get
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app1Reader
rules:
- apiGroups: ["*"] 
  resources:
    - pods
    - services
    - deployments
    - configmaps 
    - ingress
  verbs:
    - get
    - watch
    - list
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app2Operator
rules:
- apiGroups: ["*"] 
  resources:
    - pods
    - services
    - deployments
    - configmaps 
    - ingress
  verbs:
    - get
    - watch
    - list
    - create
    - delete
- apiGroups: ["*"] 
  resources:
    - secrets
  verbs:
    - get
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app2Reader
rules:
- apiGroups: ["*"] 
  resources:
    - pods
    - services
    - deployments
    - configmaps 
    - ingress
  verbs:
    - get
    - watch
    - list
