apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: microsl-microservice-svc-web
    helm.sh/chart: microservice-0.3.0
  name: microsl-microservice-svc-web
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/name: microservice
  type: ClusterIP
