kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: gitopsdemoapp
  name: smartpoetsdelivery-ingress-updater
rules:
- apiGroups: [""]
  resources: ["ingress"]
  resourceNames: ["smartpoetsdelivery-ingress"]
  verbs: ["update", "get"]
