kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app1OperatorBinding
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name:
     "usr1@mujazure.tk"
roleRef:
  kind: Role
  name: app1Operator
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app2OperatorBinding
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: "tdedic@mspassporttrask.onmicrosoft.com"
roleRef:
  kind: Role
  name: app2Operator
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app1ReaderBinding
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: "usr2@mujazure.tk"
roleRef:
  kind: Role
  name: app1Reader
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app2ReaderBinding
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: "tdedic@mspassporttrask.onmicrosoft.com"
roleRef:
  kind: Role
  name: app2Reader
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secretsOperatorBinding
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "111980ba-31f2-499d-b021-6d90b684ba54"
roleRef:
  kind: ClusterRole
  name: secretsOperator
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusteradmin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "111980ba-31f2-499d-b021-6d90b684ba54"
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "70d80737-bb83-4971-9c6a-1fe23ba85be4"
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
